spring:
  jackson:
    deserializer:
      fail-on-unknown-properties: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: optional:file:.env.${spring.profiles.active}
      
server:
  port: ${SERVER_PORT:8080}

starling:
  api:
    url: ${STARLING_API_URL:https://api-sandbox.starlingbank.com}
    token: ${STARLING_API_TOKEN}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.boot.context.config: INFO

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  show-actuator: false
  packages-to-scan: com.example.starling.roundup.controller
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
